from __future__ import annotations

import json
import stat
import subprocess
import sys
from pathlib import Path

from workflow_controller.rrc_controller import RalphRefinerController
from workflow_controller.rrc_human_gates import approve_gate_file, ensure_final_acceptance_gate, write_gate_file


ROOT = Path(__file__).resolve().parents[2]


def run_rrc(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, '-m', 'workflow_controller.rrc_controller', *args],
        cwd=str(ROOT),
        text=True,
        capture_output=True,
        check=False,
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')


def _make_ralph_workspace(tmp_path: Path) -> tuple[Path, Path]:
    workspace = tmp_path / 'workspace'
    plan_path = workspace / 'approved-plan.md'
    _write(
        plan_path,
        """# Approved Plan

## Step 1.1-delivery
- Goal: Complete delivery acceptance

### Scope
- Produce delivery artifact

### Verification
- python -c "print('verified')"
""",
    )
    _write(workspace / '.plan-ralph' / 'current-prompt.md', 'Implement delivery acceptance.')
    _write(
        workspace / '.plan-ralph' / 'session.json',
        json.dumps(
            {
                'planPath': str(plan_path),
                'completedStepIds': [],
                'promptPath': str(workspace / '.plan-ralph' / 'current-prompt.md'),
            }
        ),
    )
    return workspace, plan_path


def _generate_requirements_gate(state_dir: Path) -> None:
    draft_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert draft_result.returncode == 0, draft_result.stderr
    assert 'currentStep=WAITING_REQUIREMENTS_ACCEPTANCE' in draft_result.stdout
    assert (state_dir / 'approvals' / 'requirements-and-acceptance.md').exists()


def test_from_ralph_init_requires_requirements_acceptance_gate(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'

    result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )

    assert result.returncode == 0, result.stderr
    assert 'currentStep=REQUIREMENTS_DRAFT' in result.stdout
    assert 'nextAction=run_requirements_drafter' in result.stdout
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['humanGatesRequired'] is True
    assert state['requirementsDraftGenerated'] is False
    assert state['requirementsAccepted'] is False
    assert not (state_dir / 'approvals' / 'requirements-and-acceptance.md').exists()


def test_auto_approve_does_not_skip_requirements_acceptance_gate(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--auto-approve',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr

    result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')

    assert result.returncode == 0, result.stderr
    assert 'currentStep=WAITING_REQUIREMENTS_ACCEPTANCE' in result.stdout
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['requirementsAccepted'] is False


def test_tmux_claude_generates_requirements_gate_body(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    fake_tmux = tmp_path / 'tmux'
    _write(
        fake_tmux,
        """#!/usr/bin/env python3
import json
import os
import re
import sys
from pathlib import Path

if sys.argv[1:2] == ["paste-buffer"]:
    prompt = (Path(os.environ["RRC_RUN_DIR"]) / "prompt.md").read_text(encoding="utf-8")
    match = re.search(r"Write the Markdown body to this exact file:\\n(.+)", prompt)
    body_path = Path(match.group(1).strip())
    body_path.parent.mkdir(parents=True, exist_ok=True)
    body_path.write_text(
        "# Requirements & Acceptance Confirmation\\n\\n"
        "## 1. Requirements\\n- Generated by Claude from Ralph context.\\n\\n"
        "## 2. User Journeys\\n- User completes delivery acceptance.\\n\\n"
        "## 3. Acceptance Criteria\\n- Delivery evidence is verified.\\n\\n"
        "## 4. Test Strategy\\n- Run the declared verification command.\\n\\n"
        "## 5. Out of Scope\\n- Future units.\\n\\n"
        "## 6. Human Review Checklist\\n- [ ] Draft reviewed.\\n",
        encoding="utf-8",
    )
    Path(os.environ["RRC_RUN_DONE_FILE"]).write_text(
        json.dumps({"status": "done", "summary": "requirements generated", "run_id": os.environ["RRC_RUN_ID"]}),
        encoding="utf-8",
    )
""",
    )
    fake_tmux.chmod(fake_tmux.stat().st_mode | stat.S_IXUSR)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--runner',
        'tmux-claude',
        '--tmux-target',
        '1.2',
        '--agent',
        str(fake_tmux),
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr

    result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')

    assert result.returncode == 0, result.stderr
    assert 'currentStep=WAITING_REQUIREMENTS_ACCEPTANCE' in result.stdout
    gate_content = (state_dir / 'approvals' / 'requirements-and-acceptance.md').read_text(encoding='utf-8')
    assert 'Generated by Claude from Ralph context.' in gate_content
    assert 'Status: pending' in gate_content
    summary = json.loads((state_dir / 'artifacts' / 'requirements-draft' / 'requirements-draft-summary.json').read_text(encoding='utf-8'))
    assert summary['mode'] == 'tmux-claude'


def test_revise_requirements_gate_reruns_tmux_drafter_with_human_feedback(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    fake_tmux = tmp_path / 'tmux'
    _write(
        fake_tmux,
        """#!/usr/bin/env python3
import json
import os
import re
import sys
from pathlib import Path

if sys.argv[1:2] == ["paste-buffer"]:
    prompt = (Path(os.environ["RRC_RUN_DIR"]) / "prompt.md").read_text(encoding="utf-8")
    match = re.search(r"Write the Markdown body to this exact file:\\n(.+)", prompt)
    if match:
        body_path = Path(match.group(1).strip())
        body_path.parent.mkdir(parents=True, exist_ok=True)
        if "please add retry path" in prompt:
            requirement = "Revised by Claude from human feedback."
            journey = "User retries after a temporary failure."
        else:
            requirement = "Initial Claude draft."
            journey = "User completes delivery acceptance."
        body_path.write_text(
            "# Requirements & Acceptance Confirmation\\n\\n"
            f"## 1. Requirements\\n- {requirement}\\n\\n"
            f"## 2. User Journeys\\n- {journey}\\n\\n"
            "## 3. Acceptance Criteria\\n- Delivery evidence is verified.\\n\\n"
            "## 4. Test Strategy\\n- Run the declared verification command.\\n\\n"
            "## 5. Out of Scope\\n- Future units.\\n\\n"
            "## 6. Human Review Checklist\\n- [ ] Draft reviewed.\\n",
            encoding="utf-8",
        )
        Path(os.environ["RRC_RUN_DONE_FILE"]).write_text(
            json.dumps({"status": "done", "summary": "requirements generated", "run_id": os.environ["RRC_RUN_ID"]}),
            encoding="utf-8",
        )
        raise SystemExit(0)
raise SystemExit(0)
""",
    )
    fake_tmux.chmod(fake_tmux.stat().st_mode | stat.S_IXUSR)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--runner',
        'tmux-claude',
        '--tmux-target',
        '1.2',
        '--agent',
        str(fake_tmux),
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr
    draft_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert draft_result.returncode == 0, draft_result.stderr

    gate_path = state_dir / 'approvals' / 'requirements-and-acceptance.md'
    gate_path.write_text(
        gate_path.read_text(encoding='utf-8').replace(
            'Initial Claude draft.',
            'Initial Claude draft.\n\nReviewer note: please add retry path.',
        ),
        encoding='utf-8',
    )

    result = run_rrc('revise', '--state-dir', str(state_dir), '--gate', 'requirements')

    assert result.returncode == 0, result.stderr
    assert 'gate=requirements status=revised' in result.stdout
    gate_content = gate_path.read_text(encoding='utf-8')
    assert 'Revised by Claude from human feedback.' in gate_content
    assert 'User retries after a temporary failure.' in gate_content
    assert 'Status: pending' in gate_content
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['currentStep'] == 'WAITING_REQUIREMENTS_ACCEPTANCE'
    assert state['requirementsAccepted'] is False


def test_revise_requirements_gate_can_rewind_from_unit_plan_approval(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr
    _generate_requirements_gate(state_dir)
    approve_gate_file(state_dir / 'approvals' / 'requirements-and-acceptance.md', actor='tester')
    req_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert req_result.returncode == 0, req_result.stderr
    assert 'currentStep=UNIT_PLAN_DRAFT' in req_result.stdout
    unit_plan_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert unit_plan_result.returncode == 0, unit_plan_result.stderr
    assert 'currentStep=WAITING_UNIT_PLAN_APPROVAL' in unit_plan_result.stdout

    gate_path = state_dir / 'approvals' / 'requirements-and-acceptance.md'
    gate_path.write_text(
        gate_path.read_text(encoding='utf-8').replace(
            'Requirements are accurate.',
            'Requirements need one more revision note.',
        ),
        encoding='utf-8',
    )

    result = run_rrc('revise', '--state-dir', str(state_dir), '--gate', 'requirements')

    assert result.returncode == 0, result.stderr
    assert 'gate=requirements status=revised' in result.stdout
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['currentStep'] == 'WAITING_REQUIREMENTS_ACCEPTANCE'
    assert state['requirementsAccepted'] is False
    assert state['unitPlanAccepted'] is False


def test_revise_unit_plan_gate_reruns_tmux_drafter_with_human_feedback(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    fake_tmux = tmp_path / 'tmux'
    _write(
        fake_tmux,
        """#!/usr/bin/env python3
import json
import os
import re
import sys
from pathlib import Path

if sys.argv[1:2] == ["paste-buffer"]:
    prompt = (Path(os.environ["RRC_RUN_DIR"]) / "prompt.md").read_text(encoding="utf-8")
    match = re.search(r"Write the Markdown body to this exact file:\\n(.+)", prompt)
    if not match:
        match = re.search(r"Write the Unit Plan Markdown body to this exact file:\\n(.+)", prompt)
    if match:
        body_path = Path(match.group(1).strip())
        body_path.parent.mkdir(parents=True, exist_ok=True)
        if "Unit Plan" in prompt:
            if "please split closure evidence" in prompt:
                unit_line = "Revised unit plan with separate closure evidence."
                unit_json = (
                    '{"currentUnitId":"target-1-1",'
                    '"objectiveCoverage":[{"objective":"Delivery objective","units":["target-1-1","target-1-1-e2e"],"status":"partial"}],'
                    '"units":[{"id":"target-1-1","name":"Implementation","passes":false},'
                    '{"id":"target-1-1-e2e","name":"Closure evidence","passes":false,"workflow_validation_level":"closure"}]}'
                )
            else:
                unit_line = "Initial unit plan."
                unit_json = (
                    '{"currentUnitId":"target-1-1",'
                    '"objectiveCoverage":[{"objective":"Delivery objective","units":["target-1-1"],"status":"partial"}],'
                    '"units":[{"id":"target-1-1","name":"Implementation","passes":false}]}'
                )
            body = (
                "# Unit Plan Confirmation\\n\\n"
                "## Objective Coverage Matrix\\n- Delivery objective mapped.\\n\\n"
                f"## Units\\n- {unit_line}\\n\\n"
                "## Controller State Patch\\n\\n"
                "```json\\n"
                f"{unit_json}\\n"
                "```\\n\\n"
                "## Human Review Checklist\\n- [ ] Unit plan reviewed.\\n"
            )
        else:
            body = (
                "# Requirements & Acceptance Confirmation\\n\\n"
                "## 1. Requirements\\n- Generated requirements.\\n\\n"
                "## 2. User Journeys\\n- Generated journey.\\n\\n"
                "## 3. Acceptance Criteria\\n- Generated acceptance.\\n\\n"
                "## 4. Test Strategy\\n- Generated tests.\\n\\n"
                "## 5. Out of Scope\\n- Future units.\\n\\n"
                "## 6. Human Review Checklist\\n- [ ] Requirements reviewed.\\n"
            )
        body_path.write_text(body, encoding="utf-8")
        Path(os.environ["RRC_RUN_DONE_FILE"]).write_text(
            json.dumps({"status": "done", "summary": "draft generated", "run_id": os.environ["RRC_RUN_ID"]}),
            encoding="utf-8",
        )
        raise SystemExit(0)
raise SystemExit(0)
""",
    )
    fake_tmux.chmod(fake_tmux.stat().st_mode | stat.S_IXUSR)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--runner',
        'tmux-claude',
        '--tmux-target',
        '1.2',
        '--agent',
        str(fake_tmux),
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr
    _generate_requirements_gate(state_dir)
    approve_gate_file(state_dir / 'approvals' / 'requirements-and-acceptance.md', actor='tester')
    req_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert req_result.returncode == 0, req_result.stderr
    unit_plan_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert unit_plan_result.returncode == 0, unit_plan_result.stderr

    gate_path = state_dir / 'approvals' / 'unit-plan.md'
    gate_path.write_text(
        gate_path.read_text(encoding='utf-8').replace(
            'Initial unit plan.',
            'Initial unit plan.\n\nReviewer note: please split closure evidence.',
        ),
        encoding='utf-8',
    )

    result = run_rrc('revise', '--state-dir', str(state_dir), '--gate', 'unit-plan')

    assert result.returncode == 0, result.stderr
    assert 'gate=unit-plan status=revised' in result.stdout
    gate_content = gate_path.read_text(encoding='utf-8')
    assert 'Revised unit plan with separate closure evidence.' in gate_content
    assert 'target-1-1-e2e' in gate_content
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['currentStep'] == 'WAITING_UNIT_PLAN_APPROVAL'
    assert state['unitPlanAccepted'] is False


def test_requirements_and_unit_plan_gates_must_be_approved_before_scope(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr

    _generate_requirements_gate(state_dir)
    approve_gate_file(state_dir / 'approvals' / 'requirements-and-acceptance.md', actor='tester')
    req_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert req_result.returncode == 0, req_result.stderr
    assert 'currentStep=UNIT_PLAN_DRAFT' in req_result.stdout

    unit_plan_draft_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert unit_plan_draft_result.returncode == 0, unit_plan_draft_result.stderr
    assert 'currentStep=WAITING_UNIT_PLAN_APPROVAL' in unit_plan_draft_result.stdout
    assert (state_dir / 'approvals' / 'unit-plan.md').exists()

    approve_gate_file(state_dir / 'approvals' / 'unit-plan.md', actor='tester')
    plan_result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')
    assert plan_result.returncode == 0, plan_result.stderr
    assert 'currentStep=PLAN_CREATED' in plan_result.stdout
    assert 'nextAction=require_scope_approval' in plan_result.stdout


def test_unit_plan_approval_applies_controller_state_patch(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'old-unit',
            'currentStep': 'WAITING_UNIT_PLAN_APPROVAL',
            'lastVerifiedStep': 'PLAN_CREATED',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': False,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': False,
            'unitPlanDraftGenerated': True,
            'objectiveCoverage': [
                {'objective': 'Old objective', 'units': ['old-unit'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'old-unit', 'name': 'Old unit', 'passes': False},
            ],
        },
        force=True,
    )
    gate_path = state_dir / 'approvals' / 'unit-plan.md'
    write_gate_file(
        gate_path,
        """# Unit Plan Confirmation

## Objective Coverage Matrix
- Delivery objective -> unit-a, unit-b

## Units
### unit-a - Implementation

### unit-b - E2E closure

## Controller State Patch

```json
{
  "currentUnitId": "unit-a",
  "objectiveCoverage": [
    {
      "objective": "Delivery objective",
      "units": ["unit-a", "unit-b"],
      "status": "partial"
    }
  ],
  "units": [
    {
      "id": "unit-a",
      "name": "Implementation",
      "passes": false,
      "scope": ["Implement the delivery path"],
      "verification_commands": ["pytest tests/test_delivery.py -q"]
    },
    {
      "id": "unit-b",
      "name": "E2E closure",
      "passes": false,
      "workflow_validation_level": "closure",
      "verification_commands": ["pytest tests/e2e/test_delivery.py -q"]
    }
  ]
}
```

## Human Review Checklist
- [ ] Reviewed.
""",
    )
    approve_gate_file(gate_path, actor='tester')

    state = controller.run_once()

    assert state['currentStep'] == 'PLAN_CREATED'
    assert state['unitPlanAccepted'] is True
    assert state['currentUnitId'] == 'unit-a'
    assert [unit['id'] for unit in state['units']] == ['unit-a', 'unit-b']
    assert state['units'][0]['verification_commands'] == ['pytest tests/test_delivery.py -q']
    assert state['objectiveCoverage'] == [
        {'objective': 'Delivery objective', 'units': ['unit-a', 'unit-b'], 'status': 'partial'},
    ]


def test_unit_plan_patch_can_preserve_completed_existing_units_in_coverage(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'target-v2-1',
            'currentStep': 'WAITING_UNIT_PLAN_APPROVAL',
            'lastVerifiedStep': 'PLAN_CREATED',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': False,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': False,
            'unitPlanDraftGenerated': True,
            'objectiveCoverage': [
                {'objective': 'Old objective', 'units': ['old-unit'], 'status': 'covered'},
                {'objective': 'Target objective', 'units': ['target-v2-1'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'old-unit', 'name': 'Old unit', 'passes': True},
                {'id': 'target-v2-1', 'name': 'Target placeholder', 'passes': False},
            ],
        },
        force=True,
    )
    gate_path = state_dir / 'approvals' / 'unit-plan.md'
    write_gate_file(
        gate_path,
        """# Unit Plan Confirmation

## Controller State Patch

```json
{
  "currentUnitId": "unit-a",
  "objectiveCoverage": [
    {"objective": "Old objective", "units": ["old-unit"], "status": "covered"},
    {"objective": "Delivery objective", "units": ["unit-a"], "status": "partial"}
  ],
  "units": [
    {
      "id": "unit-a",
      "name": "Implementation",
      "passes": false,
      "scope": ["Implement the delivery path"],
      "verification_commands": ["pytest tests/test_delivery.py -q"]
    }
  ]
}
```
""",
    )
    approve_gate_file(gate_path, actor='tester')

    state = controller.run_once()

    assert state['currentStep'] == 'PLAN_CREATED'
    assert state['unitPlanAccepted'] is True
    assert state['currentUnitId'] == 'unit-a'
    assert [unit['id'] for unit in state['units']] == ['unit-a', 'old-unit']
    assert state['units'][1]['passes'] is True
    assert state['objectiveCoverage'] == [
        {'objective': 'Old objective', 'units': ['old-unit'], 'status': 'covered'},
        {'objective': 'Delivery objective', 'units': ['unit-a'], 'status': 'partial'},
    ]


def test_unit_plan_approval_without_controller_state_patch_stays_waiting(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'unit-01',
            'currentStep': 'WAITING_UNIT_PLAN_APPROVAL',
            'lastVerifiedStep': 'PLAN_CREATED',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': False,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': False,
            'unitPlanDraftGenerated': True,
            'objectiveCoverage': [
                {'objective': 'Delivery objective', 'units': ['unit-01'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'unit-01', 'name': 'Delivery', 'passes': False},
            ],
        },
        force=True,
    )
    gate_path = state_dir / 'approvals' / 'unit-plan.md'
    write_gate_file(
        gate_path,
        """# Unit Plan Confirmation

## Objective Coverage Matrix
- Delivery objective -> unit-01

## Units
### unit-01 - Delivery

## Human Review Checklist
- [ ] Reviewed.
""",
    )
    approve_gate_file(gate_path, actor='tester')

    state = controller.run_once()

    assert state['currentStep'] == 'WAITING_UNIT_PLAN_APPROVAL'
    assert state['unitPlanAccepted'] is False
    assert 'Controller State Patch' in state['blockedReason']


def test_unit_plan_approval_enforces_required_test_strategy_layers(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'unit-api',
            'currentStep': 'WAITING_UNIT_PLAN_APPROVAL',
            'lastVerifiedStep': 'PLAN_CREATED',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': False,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': False,
            'unitPlanDraftGenerated': True,
            'objectiveCoverage': [
                {'objective': 'Delivery objective', 'units': ['unit-api'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'unit-api', 'name': 'API delivery', 'passes': False},
            ],
        },
        force=True,
    )
    requirements_path = state_dir / 'approvals' / 'requirements-and-acceptance.md'
    write_gate_file(
        requirements_path,
        """# Requirements & Acceptance Confirmation

## 1. Requirements
- Delivery works.

## 2. User Journeys
- User completes delivery.

## 3. Acceptance Criteria
- Delivery evidence exists.

## 4. Test Strategy
- Unit tests cover parser behavior.
- E2E tests cover browser delivery.

## 5. Out of Scope
- Future work.
""",
    )
    approve_gate_file(requirements_path, actor='tester')
    unit_plan_path = state_dir / 'approvals' / 'unit-plan.md'
    write_gate_file(
        unit_plan_path,
        """# Unit Plan Confirmation

## Units
### unit-api - API delivery
- Verification commands:
  - `pytest tests/test_parser.py -q`

## Controller State Patch

```json
{
  "currentUnitId": "unit-api",
  "objectiveCoverage": [
    {"objective": "Delivery objective", "units": ["unit-api"], "status": "partial"}
  ],
  "units": [
    {
      "id": "unit-api",
      "name": "API delivery",
      "passes": false,
      "verification_commands": ["pytest tests/test_parser.py -q"]
    }
  ]
}
```
""",
    )
    approve_gate_file(unit_plan_path, actor='tester')

    state = controller.run_once()

    assert state['currentStep'] == 'WAITING_UNIT_PLAN_APPROVAL'
    assert state['unitPlanAccepted'] is False
    assert 'test strategy' in state['blockedReason']
    assert 'e2e' in state['blockedReason'].lower()


def test_unit_plan_approval_rejects_playwright_command_without_database_env(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'unit-e2e',
            'currentStep': 'WAITING_UNIT_PLAN_APPROVAL',
            'lastVerifiedStep': 'PLAN_CREATED',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': False,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': False,
            'unitPlanDraftGenerated': True,
            'objectiveCoverage': [
                {'objective': 'Delivery objective', 'units': ['unit-e2e'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'unit-e2e', 'name': 'E2E delivery', 'passes': False},
            ],
        },
        force=True,
    )
    requirements_path = state_dir / 'approvals' / 'requirements-and-acceptance.md'
    write_gate_file(
        requirements_path,
        """# Requirements & Acceptance Confirmation

## 4. Test Strategy
- Playwright E2E tests cover browser delivery.
""",
    )
    approve_gate_file(requirements_path, actor='tester')
    unit_plan_path = state_dir / 'approvals' / 'unit-plan.md'
    write_gate_file(
        unit_plan_path,
        """# Unit Plan Confirmation

## Units
### unit-e2e - E2E delivery
- Verification commands:
  - `pnpm exec playwright test tests/e2e/delivery.spec.ts`

## Controller State Patch

```json
{
  "currentUnitId": "unit-e2e",
  "objectiveCoverage": [
    {"objective": "Delivery objective", "units": ["unit-e2e"], "status": "partial"}
  ],
  "units": [
    {
      "id": "unit-e2e",
      "name": "E2E delivery",
      "passes": false,
      "verification_commands": ["pnpm exec playwright test tests/e2e/delivery.spec.ts"]
    }
  ]
}
```
""",
    )
    approve_gate_file(unit_plan_path, actor='tester')

    state = controller.run_once()

    assert state['currentStep'] == 'WAITING_UNIT_PLAN_APPROVAL'
    assert state['unitPlanAccepted'] is False
    assert 'verification_env' in state['blockedReason']
    assert 'DATABASE_URL' in state['blockedReason']


def test_final_acceptance_gate_summarizes_execution_evidence(tmp_path: Path) -> None:
    state = {
        'task_id': 'delivery',
        'currentUnitId': 'unit-01',
        'currentStep': 'WAITING_FINAL_ACCEPTANCE',
        'status': 'active',
        'objectiveCoverage': [
            {'objective': 'Delivery objective', 'units': ['unit-01'], 'status': 'covered'},
        ],
    }
    artifacts_dir = tmp_path / 'artifacts'
    unit_dir = artifacts_dir / 'unit-01'
    unit_dir.mkdir(parents=True)
    (unit_dir / 'changed-files.txt').write_text('src/delivery.py\ntests/test_delivery.py\n', encoding='utf-8')
    (unit_dir / 'builder-summary.json').write_text(
        json.dumps({
            'runner_status': 'done',
            'done_payload': {'summary': 'Delivery implemented'},
            'changed_files': ['src/delivery.py', 'tests/test_delivery.py'],
        }),
        encoding='utf-8',
    )
    (unit_dir / 'review.json').write_text(
        json.dumps({'passed': True, 'issues': [], 'reviewer': 'real-runtime-reviewer'}),
        encoding='utf-8',
    )
    (unit_dir / 'verification.json').write_text(
        json.dumps({
            'passed': True,
            'commands': ['pytest tests/test_delivery.py -q'],
            'results': [
                {'command': 'pytest tests/test_delivery.py -q', 'returncode': 0, 'ok': True, 'stdout': '1 passed'}
            ],
        }),
        encoding='utf-8',
    )

    gate_path = ensure_final_acceptance_gate(state, tmp_path / 'approvals', artifacts_dir, force=True)

    content = gate_path.read_text(encoding='utf-8')
    assert '## Evidence Summary' in content
    assert 'Delivery implemented' in content
    assert '`pytest tests/test_delivery.py -q` -> passed' in content
    assert '`src/delivery.py`' in content
    assert 'Review: passed' in content


def test_tmux_claude_generates_unit_plan_gate_body_after_requirements_approval(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    fake_tmux = tmp_path / 'tmux'
    _write(
        fake_tmux,
        """#!/usr/bin/env python3
import json
import os
import re
import sys
from pathlib import Path

if sys.argv[1:2] == ["paste-buffer"]:
    prompt = (Path(os.environ["RRC_RUN_DIR"]) / "prompt.md").read_text(encoding="utf-8")
    match = re.search(r"Write the Markdown body to this exact file:\\n(.+)", prompt)
    if not match:
        match = re.search(r"Write the Unit Plan Markdown body to this exact file:\\n(.+)", prompt)
    body_path = Path(match.group(1).strip())
    body_path.parent.mkdir(parents=True, exist_ok=True)
    if "Unit Plan" in prompt:
        body = (
            "# Unit Plan Confirmation\\n\\n"
            "## Objective Coverage Matrix\\n- Claude generated unit coverage.\\n\\n"
            "## Units\\n### target-1-1 - Claude generated unit\\n"
            "- Workflow validation level: `closure`\\n"
            "- Scope:\\n  - Implement target acceptance.\\n"
            "- Verification commands:\\n  - `python -c \\"print('verified')\\"`\\n\\n"
            "## Human Review Checklist\\n- [ ] Unit plan reviewed.\\n"
        )
    else:
        body = (
            "# Requirements & Acceptance Confirmation\\n\\n"
            "## 1. Requirements\\n- Generated requirements.\\n\\n"
            "## 2. User Journeys\\n- Generated journey.\\n\\n"
            "## 3. Acceptance Criteria\\n- Generated acceptance.\\n\\n"
            "## 4. Test Strategy\\n- Generated tests.\\n\\n"
            "## 5. Out of Scope\\n- Future units.\\n\\n"
            "## 6. Human Review Checklist\\n- [ ] Requirements reviewed.\\n"
        )
    body_path.write_text(body, encoding="utf-8")
    Path(os.environ["RRC_RUN_DONE_FILE"]).write_text(
        json.dumps({"status": "done", "summary": "draft generated", "run_id": os.environ["RRC_RUN_ID"]}),
        encoding="utf-8",
    )
""",
    )
    fake_tmux.chmod(fake_tmux.stat().st_mode | stat.S_IXUSR)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--runner',
        'tmux-claude',
        '--tmux-target',
        '1.2',
        '--agent',
        str(fake_tmux),
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr
    _generate_requirements_gate(state_dir)
    approve_gate_file(state_dir / 'approvals' / 'requirements-and-acceptance.md', actor='tester')

    result = run_rrc('run', '--state-dir', str(state_dir), '--until-done', '--auto-approve')

    assert result.returncode == 0, result.stderr
    assert 'currentStep=WAITING_UNIT_PLAN_APPROVAL' in result.stdout
    unit_plan_content = (state_dir / 'approvals' / 'unit-plan.md').read_text(encoding='utf-8')
    assert 'Claude generated unit coverage.' in unit_plan_content
    assert 'Status: pending' in unit_plan_content
    summary = json.loads((state_dir / 'artifacts' / 'unit-plan-draft' / 'unit-plan-draft-summary.json').read_text(encoding='utf-8'))
    assert summary['mode'] == 'tmux-claude'


def test_approve_command_updates_markdown_gate_hash(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr

    _generate_requirements_gate(state_dir)
    result = run_rrc(
        'approve',
        '--state-dir',
        str(state_dir),
        '--gate',
        'requirements',
        '--actor',
        'tester',
    )

    assert result.returncode == 0, result.stderr
    assert 'gate=requirements status=approved' in result.stdout
    gate_content = (state_dir / 'approvals' / 'requirements-and-acceptance.md').read_text(encoding='utf-8')
    assert 'Status: approved' in gate_content
    assert 'Confirmed by: tester' in gate_content
    assert 'Content hash: sha256:' in gate_content


def test_final_acceptance_approve_command_requires_final_waiting_step(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr

    result = run_rrc(
        'approve',
        '--state-dir',
        str(state_dir),
        '--gate',
        'final-acceptance',
        '--actor',
        'tester',
    )

    assert result.returncode != 0
    assert 'Final acceptance can only be approved at WAITING_FINAL_ACCEPTANCE' in result.stderr
    assert 'Traceback' not in result.stderr


def test_gate_approval_becomes_stale_when_content_changes(tmp_path: Path) -> None:
    workspace, _ = _make_ralph_workspace(tmp_path)
    state_dir = tmp_path / '.rrc-controller'
    init_result = run_rrc(
        'init',
        '--state-dir',
        str(state_dir),
        '--workspace-dir',
        str(workspace),
        '--from-ralph',
        '--target',
        '1.1',
        '--force',
    )
    assert init_result.returncode == 0, init_result.stderr
    _generate_requirements_gate(state_dir)
    gate_path = state_dir / 'approvals' / 'requirements-and-acceptance.md'
    approve_gate_file(gate_path, actor='tester')
    gate_path.write_text(
        gate_path.read_text(encoding='utf-8').replace(
            'Requirements are accurate.',
            'Requirements have changed.',
        ),
        encoding='utf-8',
    )

    result = run_rrc('run', '--state-dir', str(state_dir), '--auto-approve')

    assert result.returncode == 0, result.stderr
    assert 'currentStep=WAITING_REQUIREMENTS_ACCEPTANCE' in result.stdout
    state = json.loads((state_dir / 'session.json').read_text(encoding='utf-8'))
    assert state['requirementsAccepted'] is False


def test_final_acceptance_gate_blocks_done_until_approved(tmp_path: Path) -> None:
    state_dir = tmp_path / '.rrc-controller'
    controller = RalphRefinerController(state_dir=state_dir, auto_approve=True)
    controller.init_state(
        {
            'task_id': 'delivery',
            'currentUnitId': 'unit-01',
            'currentStep': 'UNIT_COMPLETE',
            'lastVerifiedStep': 'VERIFY_UNIT',
            'status': 'active',
            'requestedOutcome': 'usable-system',
            'feasibleOutcome': 'usable-system',
            'scopeApproved': True,
            'autoApprove': True,
            'humanGatesRequired': True,
            'requirementsAccepted': True,
            'unitPlanAccepted': True,
            'finalAcceptanceAccepted': False,
            'objectiveCoverage': [
                {'objective': 'Deliver usable workflow', 'units': ['unit-01'], 'status': 'partial'},
            ],
            'units': [
                {'id': 'unit-01', 'passes': False},
            ],
        },
        force=True,
    )

    state = controller.run_once()

    assert state['currentStep'] == 'WAITING_FINAL_ACCEPTANCE'
    assert state['nextAllowedActions'] == ['check_final_acceptance']
    final_gate = state_dir / 'approvals' / 'final-acceptance.md'
    assert final_gate.exists()

    state = controller.run_once()
    assert state['currentStep'] == 'WAITING_FINAL_ACCEPTANCE'
    assert state['finalAcceptanceAccepted'] is False

    approve_gate_file(final_gate, actor='tester')
    state = controller.run_once()
    assert state['currentStep'] == 'RELEASE_GATE'
    assert state['nextAllowedActions'] == ['require_release_approval']

    state = controller.run_once()
    assert state['currentStep'] == 'DONE'
    assert state['status'] == 'done'
